name: Hello World Training Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  package-and-publish:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latestNV, thanks for using GitHub Actions!"
