name: Hello World Training Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]

jobs:
  greet:
    env:
      MY_ENV: "John Doe"
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"

  farewell:
    needs: greet  # Це залежність: завдання виконується після greet
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye $MY_ENV, thanks for using GitHub Actions!"
