name: Hello World Training Workflow
on:
  workflow_dispatch:
jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      MY_ENV: "John Doe"
    steps:
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
      - run: ls -l
      - name: Checkout repository
        uses: actions/checkout@v3  # Latest version recommended
      - run: ls -l
